{% set version = "3.1.2" %}

package:
  name: libjpeg-turbo
  version: {{ version }}

source:
  url: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/{{ version }}.tar.gz
  sha256: 560f6338b547544c4f9721b18d8b87685d433ec78b3c644c70d77adad22c55e6

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libjpeg-turbo', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - yasm
  run_constrained:
    - jpeg <0.0.0a

test:
  files:
    - testorig.jpg
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
  home: http://www.libjpeg-turbo.org/
  license: IJG AND BSD-3-Clause AND Zlib
  license_file: LICENSE.md
  summary: IJG JPEG compliant runtime library with SIMD and other optimizations
  dev_url: https://github.com/libjpeg-turbo/libjpeg-turbo

extra:
  recipe-maintainers:
    - valgur
    - sdvillal
    - carlodri
    - hmaarrfk
