{% set version = "2.1.5.1" %}

package:
  name: libjpeg-turbo
  version: {{ version }}

source:
  url: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/{{ version }}.tar.gz
  sha256: 61846251941e5791005fb7face196eec24541fce04f12570c308557529e92c75

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('libjpeg-turbo', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - yasm
  run_constrained:
    - jpeg <0.0.0a

test:
  files:
    - testorig.jpg
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
  home: http://www.libjpeg-turbo.org/
  dev_url: https://github.com/libjpeg-turbo/libjpeg-turbo
  license: IJG AND BSD-3-Clause AND Zlib
  license_file: LICENSE.md
  summary: IJG JPEG compliant runtime library with SIMD and other optimizations

extra:
  recipe-maintainers:
    - valgur
    - sdvillal
    - carlodri
    - hmaarrfk
