{% set version = "1.5.2" %}

package:
    name: libjpeg-turbo
    version: {{ version }}

source:
    fn: libjpeg-turbo-{{ version }}.tar.gz
    url: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/{{ version }}.tar.gz
    sha256: d08b57310725155b6b81d7a97f57df198ab72098e851e19b633a57a35f7feb0d

build:
    number: 0
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]
        - vc14  # [win and py36]

requirements:
    build:
        - python  # [win]
        - cmake  # [win]
        - msinttypes  # [win]
        - autoconf  # [unix]
        - automake  # [unix]
        - libtool  # [unix]
        - yasm
        - vc   9  # [win and py27]
        - vc  10  # [win and py34]
        - vc  14  # [win and py35]
        - vc  14  # [win and py36]

    run:
        - vc   9  # [win and py27]
        - vc  10  # [win and py34]
        - vc  14  # [win and py35]
        - vc  14  # [win and py36]

test:
    files:
        - testorig.jpg
    commands:
        - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
    home: http://www.libjpeg-turbo.org/
    license: IJG, modified 3-clause BSD and zlib
    summary: IJG JPEG compliant runtime library with SIMD and other optimizations
    
extra:    
    recipe-maintainers:
        - valgur
        - sdvillal
