# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "O3yqq7WQh7C6YJXx/w/+OJ8KEfBGEzmK0mV+i2yIhCUN6oqYMoixsgTXfxqXWtfSMITjLcWi6y/3GQDRl0THx4AJESl3s9CpQ/uzK985QbSfYIHF3J/hRV8odYfNDkAskgNYduyW+Fmzrzh/y+musjlODHU3SoDRmO6JPZFXSV5eUirwlVhpnJe8zJLia2h+ts3wHpVsMvZGl8HLL4T1osQbRMleArRBTLYCZPq0hKR2WatKQwk2FXr0bUYM9G1f95H73xbb6gTK2xRweRF5jzOcoBVtUArTUn75Jwgn6G8Woetn9mKDkjJQLmePRoqpJOu7U9gWhLdh9Uj/Efr3z9UBDQoj8TDZzlSVKKLPfS0N3m5PEz3Xr0UnV4h2tTYdn69XI4aaVBaekDX5oQwQ4P9ERPdAbWdGr+f+cqumcGSCbsB+6V3f6Ti9uzrnliUIBaWg9uq+2JRtQmShABm+SumIB2MQbVnSdkWzRhGhttXCWIshC96RVInUnTj7usHAwj1VawNVJRCMJ7a52aUYEWVwAXSPAsvT0sEHS+TDUUbXEWzNxEEY/mmW5OGWtIx4zUkeUzRT6fHOhPTHlkM/plgZVgYAKlEIxjErrNo15eBDjy/E/XZNTwIShfypQ2kGELkNWqu/kgAnBK0Q65f/eTP90+8hVU9FkN+FdeeujW4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
