appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: YviW8frkLxenczZOFCdEUeh0hz/Hn/zNnQ1brYtgcDqnW6XecSXo7pO3K1+ODpGe5JWosrqV1D28AOKErre9oEVfyCGP2bySwRYxoqwHjtw2KzOoytPQan2sD3IUC21vFiOsOMDseelgNoTF3clqF7vN3/fdNaOgphHsi8Ivmb5qXRfU4/KpuJj2RoTi0YRwuMv75LD16J/zFieR/kx7huamWHESZUrDCZDjuH7A3PadehSDCv9hAzw6jOTgnPSw3W621bBT/Y3nePc+jPOmZg0wIA8ulX8JfSMkbxdlZnWX0D2j3cNnS+4+233l6dIiRFJcPOviuKYq4+EbagVR1/af8DLsk5TvBqcd876XfWKEUt1NXwAdRWVb1kgjyowQTUgLUFWxQPyxz3a5N6lM/qgyA8U1gKISbKPG3ieoYqAUYqPthOKybZAKJtzk/+UfzCmsYP4RWQ1ykXHu0zhl0v4WL3C3KB97SjyV5jBeB/WSs5l9mYidd8o43cKzCXFYtKXUWRt3WT4cTfMrMrZqBV8bTMc+EvDklkW1V4jzalBATaMh7A05sWMOrnCXO3+0LGetcY4iPsPFZLy2+a1xHOQANq/yNoHCPFjE4teqTDJ4uXHs6WO/ZZ9bMme2LMkedTUYlJ/xb5G0qEC52zuEqvOgiCWPg34y8VSpQMTMH6k=}
